local crystalData = {
    ["Blue Crystal"] = {
        {name = "Blue Birdie", rarity = "Basic", Type = "Pet"},
        {name = "Orange Hedgehog", rarity = "Basic", Type = "Pet"},
        {name = "Red Kitty", rarity = "Basic", Type = "Pet"},
        {name = "Dark Vampy", rarity = "Advanced", Type = "Pet"},
        {name = "Blue Bunny", rarity = "Basic", Type = "Pet"},
        {name = "Red Aura", rarity = "Basic", Type = "Aura"},
        {name = "Blue Aura", rarity = "Basic", Type = "Aura"},
        {name = "Green Aura", rarity = "Basic", Type = "Aura"},
        {name = "Purple Aura", rarity = "Basic", Type = "Aura"},
        {name = "Red Aura", rarity = "Basic", Type = "Aura"},
        {name = "Yellow Aura", rarity = "Basic", Type = "Aura"},
    },
    ["Green Crystal"] = {
        {name = "Silver Dog", rarity = "Basic", Type = "Pet"},
        {name = "Green Aura", rarity = "Advanced", Type = "Aura"},
        {name = "Dark Golem", rarity = "Advanced", Type = "Pet"},
        {name = "Green Butterfly", rarity = "Advanced", Type = "Pet"},
        {name = "Crimson Falcon", rarity = "Rare", Type = "Pet"},
        {name = "Red Aura", rarity = "Basic", Type = "Aura"},
        {name = "Blue Aura", rarity = "Basic", Type = "Aura"},
        {name = "Green Aura", rarity = "Basic", Type = "Aura"},
        {name = "Purple Aura", rarity = "Basic", Type = "Aura"},
        {name = "Red Aura", rarity = "Basic", Type = "Aura"},
        {name = "Yellow Aura", rarity = "Basic", Type = "Aura"},
    },
    ["Frost Crystal"] = {
        {name = "Yellow Butterfly", rarity = "Advanced", Type = "Pet"},
        {name = "Purple Dragon", rarity = "Rare", Type = "Pet"},
        {name = "Blue Pheonix", rarity = "Epic", Type = "Pet"},
        {name = "Orange Pegasus", rarity = "Rare", Type = "Pet"},
        {name = "Lightning", rarity = "Rare", Type = "Aura"},
        {name = "Electro", rarity = "Advanced", Type = "Aura"},
    },
    ["Mythical Crystal"] = {
        {name = "Purple Falcon", rarity = "Rare", Type = "Pet"},
        {name = "Red Dragon", rarity = "Rare", Type = "Pet"},
        {name = "Blue Firecaster", rarity = "Epic", Type = "Pet"},
        {name = "Golden Pheonix", rarity = "Epic", Type = "Pet"},
        {name = "Power Lightning", rarity = "Rare", Type = "Aura"},
        {name = "Dark Lightning", rarity = "Epic", Type = "Aura"},
    },
    ["Inferno Crystal"] = {
        {name = "Red Firecaster", rarity = "Epic", Type = "Pet"},
        {name = "Infernal Dragon", rarity = "Unique", Type = "Pet"},
        {name = "White Pegasus", rarity = "Rare", Type = "Pet"},
        {name = "Golden Pheonix", rarity = "Epic", Type = "Pet"},
        {name = "Inferno", rarity = "Epic", Type = "Aura"},
        {name = "Dark Storm", rarity = "Unique", Type = "Aura"},
    },
    ["Legends Crystal"] = {
        {name = "Ultra Birdie", rarity = "Unique", Type = "Pet"},
        {name = "Magic Butterfly", rarity = "Unique", Type = "Pet"},
        {name = "Green Firecaster", rarity = "Epic", Type = "Pet"},
        {name = "White Pheonix", rarity = "Epic", Type = "Pet"},
        {name = "Supernova", rarity = "Epic", Type = "Aura"},
        {name = "Purple Nova", rarity = "Unique", Type = "Aura"},
    },
    ["Muscle Elite Crystal"] = {
        {name = "Frostwave Legends Penguin", rarity = "Rare", Type = "Pet"},
        {name = "Phantom Genesis Dragon", rarity = "Rare", Type = "Pet"},
        {name = "Dark Legends Manticore", rarity = "Epic", Type = "Pet"},
        {name = "Ultimate Supernova Pegasus", rarity = "Epic", Type = "Pet"},
        {name = "Aether Spirit Bunny", rarity = "Unique", Type = "Pet"},
        {name = "Cybernetic Showdown Dragon", rarity = "Unique", Type = "Pet"},
    },
    ["Galaxy Oracle Crystal"] = {
        {name = "Eternal Strike Leviathan", rarity = "Rare", Type = "Pet"},
        {name = "Lightning Strike Phantom", rarity = "Epic", Type = "Pet"},
        {name = "Darkstar Hunter", rarity = "Unique", Type = "Pet"},
        {name = "Muscle King", rarity = "Unique", Type = "Aura"},
        {name = "Azure Tundra", rarity = "Epic", Type = "Aura"},
        {name = "Ultra Inferno", rarity = "Rare", Type = "Aura"},
    },
    ["Jungle Crystal"] = {
        {name = "Entropic Blast", rarity = "Unique", Type = "Aura"},
        {name = "Muscle Sensei", rarity = "Unique", Type = "Pet"},
        {name = "Grand Supernova", rarity = "Epic", Type = "Aura"},
        {name = "Neon Guardian", rarity = "Unique", Type = "Pet"},
        {name = "Eternal Megastrike", rarity = "Unique", Type = "Aura"},
        {name = "Golden Viking", rarity = "Epic", Type = "Pet"},
        {name = "Astral Electro", rarity = "Epic", Type = "Aura"},
        {name = "Dark Electro", rarity = "Epic", Type = "Aura"},
        {name = "Enchanted Mirage", rarity = "Epic", Type = "Aura"},
        {name = "Ultra Mirage", rarity = "Unique", Type = "Aura"},
        {name = "Unstable Mirage", rarity = "Unique", Type = "Aura"},
    }
}

return crystalData
