return {
    ["Blue Crystal"] = {
        "Blue Birdie | Basic",
        "Orange Hedgehog | Basic",
        "Blue Aura | Basic",
        "Green Aura | Basic",
        "Purple Aura | Basic",
        "Red Aura | Basic",
        "Yellow Aura | Basic",
        "Red Kitty | Basic",
        "Dark Vampy | Advanced",
        "Blue Bunny | Basic"
    },
    ["Green Crystal"] = {
        "Silver Dog | Basic",
        "Electro | Advanced",
        "Purple Nova | Advanced",
        "Dark Golem | Advanced",
        "Green Butterfly | Advanced",
        "Crimson Falcon | Rare",
        "Blue Aura | Basic",
        "Green Aura | Basic",
        "Purple Aura | Basic",
        "Red Aura | Basic",
        "Yellow Aura | Basic"
    },
    ["Frost Crystal"] = {
        "Electro | Advanced",
        "Purple Nova | Advanced",
        "Yellow Butterfly | Advanced",
        "Purple Dragon | Rare",
        "Blue Pheonix | Epic",
        "Astral Electro | Rare",
        "Dark Electro | Rare",
        "Power Lightning | Rare",
        "Supernova | Rare",
        "Ultra Inferno | Rare",
        "Ultra Mirage | Rare",
        "Orange Pegasus | Rare"
    },
    ["Mythical Crystal"] = {
        "Astral Electro | Rare",
        "Dark Electro | Rare",
        "Power Lightning | Rare",
        "Supernova | Rare",
        "Ultra Inferno | Rare",
        "Ultra Mirage | Rare",
        "Azure Tundra | Epic",
        "Enchanted Mirage | Epic",
        "Grand Supernova | Epic",
        "Lightning | Epic",
        "Unstable Mirage | Epic",
        "Purple Falcon | Rare",
        "Red Dragon | Rare",
        "Blue Firecaster | Epic",
        "Golden Pheonix | Epic"
    },
    ["Inferno Crystal"] = {
        "Azure Tundra | Epic",
        "Enchanted Mirage | Epic",
        "Grand Supernova | Epic",
        "Lightning | Epic",
        "Unstable Mirage | Epic",
        "Dark Lightning | Unique",
        "Dark Storm | Unique",
        "Entropic Blast | Unique",
        "Eternal Megastrike | Unique",
        "Inferno | Unique",
        "Muscle King | Unique",
        "Red Firecaster | Epic",
        "Infernal Dragon | Unique",
        "White Pegasus | Rare",
        "Golden Pheonix | Epic"
    },
    ["Legends Crystal"] = {
        "Azure Tundra | Epic",
        "Enchanted Mirage | Epic",
        "Grand Supernova | Epic",
        "Lightning | Epic",
        "Unstable Mirage | Epic",
        "Dark Lightning | Unique",
        "Dark Storm | Unique",
        "Entropic Blast | Unique",
        "Eternal Megastrike | Unique",
        "Inferno | Unique",
        "Muscle King | Unique",
        "Ultra Birdie | Unique",
        "Magic Butterfly | Unique",
        "Green Firecaster | Epic",
        "White Pheonix | Epic"
    },
    ["Muscle Elite Crystal"] = {
        "Frostwave Legends Penguin | Rare",
        "Phantom Genesis Dragon | Rare",
        "Dark Legends Manticore | Epic",
        "Ultimate Supernova Pegasus | Epic",
        "Aether Spirit Bunny | Unique",
        "Cybernetic Showdown Dragon | Unique"
    },
    ["Galaxy Oracle Crystal"] = {
        "Eternal Strike Leviathan | Rare",
        "Lightning Strike Phantom | Epic",
        "Darkstar Hunter | Unique",
        "Muscle King Aura | Unique",
        "Azure Tundra Aura | Epic",
        "Ultra Inferno Aura | Rare"
    },
    ["Jungle Crystal"] = {
        "Entropic Blast Aura | Unique",
        "Muscle Sensei | Unique",
        "Grand Supernova Aura | Epic",
        "Neon Guardian | Unique",
        "Eternal Megastrike Aura | Unique",
        "Golden Viking | Epic"
    }
}
